title: Dapao Huang's Space
page-top-title: Xinjie Huang
top-section-bg-text: <b>Live long and prosper.</b><br>生生不息 繁荣昌盛
home-subtitle: Xinjie Huang&ensp;|&ensp;黄大炮
copyright-text: '&copy; Dapao Huang 2023-2024. All Rights Reserved.'
