name: release-please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          commit-limit: 3
          # ✅ 仅创建/更新 Release PR；不打 tag、不发 GitHub Release
          skip-github-release: true
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

          # 可选：主版本前（v1 之前）允许次版本增长
#          bump-minor-pre-major: true
