name: release-please
on:
  push:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
  issues: write
concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          skip-github-release: true
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
